### ISSUE TITLE
Key State Case Mismatch

### ISSUE THREAD

**Issue by seiffert** [defionscode/ansible-iam-module#1]
The `key_state` should be case insensitive. Currently, the parameter should be one of `"Active,Inactive,create,remove"`, in `create_user` however, `key_state` is checked for `"active"`.
I think the user shouldn't have to care about case here. If you push the code to this repository, I'm happy to provide a fix as a PR - currently, I'm using a copy of the module copied to my local `library` folder.

**Comment by seiffert** [comment]
( see https://github.com/Jimdo/ansible-iam-module/commit/b933e76e7a960437dff5ebf48c862ba14ca8678d )

**Comment by nousdefions** [comment]
Yep, excellent point. I'll pull that in momentarily.

**Comment by nousdefions** [comment]
After I merged that in I just realized something. Boto is case sensitive for Active/Inactive. I'll have to mod it so that it uses `.capitalize()` method for that.
